# CD Pipeline

resources:
  pipelines:
  - pipeline: buildPipeline
    source: AzureBuildPipelineName # the CI build pipeline in Azure DevOps
    trigger:
      branches:
        include:
        - main # Trigger only for builds on the main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployToAppService
  displayName: 'Deploy to Azure App Service'
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          # Download the artifact published by the CI pipeline
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'current' # Download from the triggering build
              downloadType: 'single'
              artifactName: 'counterApp'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Deploy to Azure App Service
          - task: AzureWebApp@1
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: 'azure-connection'
              appType: 'webAppLinux'
              appName: 'my-dotnet-counter-app'
              package: '$(System.ArtifactsDirectory)/counterApp/**/*.zip'
              runtimeStack: 'DOTNETCORE|6.0'
